/**
 * 预置提供商配置数据
 * 包含常用 AI 提供商的默认配置信息
 */

export interface PresetProvider {
  id: string;
  name: string;
  nameEn?: string;
  baseUrl?: string;
  apiKeyUrl?: string;
  sdkType: string;
  authType: string;
  openaiCompatible: boolean;
  checkModel?: string;
  icon?: string;
  description?: string;
}

export const PRESET_PROVIDERS: PresetProvider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'gpt-5.2',
    description: 'OpenAI 官方 API，提供 GPT 系列模型',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    baseUrl: 'https://api.anthropic.com',
    apiKeyUrl: 'https://console.anthropic.com/settings/keys',
    sdkType: 'anthropic',
    authType: 'x-api-key',
    openaiCompatible: false,
    checkModel: 'claude-opus-4-5-20251101',
    description: 'Anthropic 官方 API，提供 Claude 系列模型',
  },
  {
    id: 'google',
    name: 'Google Gemini',
    nameEn: 'Google',
    baseUrl: 'https://generativelanguage.googleapis.com',
    apiKeyUrl: 'https://aistudio.google.com/apikey',
    sdkType: 'google',
    authType: 'query',
    openaiCompatible: false,
    checkModel: 'gemini-2.0-flash',
    description: 'Google Gemini 官方 API',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'deepseek-chat',
    description: 'DeepSeek 官方 API，提供 deepseek-chat 等模型',
  },
  {
    id: 'nvidia',
    name: 'NVIDIA',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    apiKeyUrl: 'https://build.nvidia.com/explore/discover',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'meta/llama-3.1-8b-instruct',
    description: 'NVIDIA NIM API，提供多种开源模型推理',
  },
  {
    id: 'qwen',
    name: '通义千问',
    nameEn: 'Qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKeyUrl: 'https://bailian.console.aliyun.com/?apiKey=1#/api-key',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'qwen-plus',
    description: '阿里云通义千问官方 API',
  },
  {
    id: 'zhipu',
    name: '智谱',
    nameEn: 'ZhiPu',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    apiKeyUrl: 'https://open.bigmodel.cn/usercenter/api-keys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'glm-4',
    description: '智谱 AI 官方 API，提供 GLM 系列模型',
  },
  {
    id: 'moonshot',
    name: 'Moonshot',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'moonshot-v1-8k',
    description: 'Moonshot（Kimi）官方 API',
  },
  {
    id: 'minimax',
    name: 'Minimax',
    baseUrl: 'https://api.minimaxi.com/v1',
    apiKeyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'MiniMax-Text-01',
    description: 'Minimax 官方 API',
  },
  {
    id: 'groq',
    name: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKeyUrl: 'https://console.groq.com/keys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'llama-3.3-70b-versatile',
    description: 'Groq 高速推理 API',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    baseUrl: 'https://api.mistral.ai',
    apiKeyUrl: 'https://console.mistral.ai/api-keys/',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'mistral-large-latest',
    description: 'Mistral AI 官方 API',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyUrl: 'https://openrouter.ai/settings/keys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'openai/gpt-4o',
    description: 'OpenRouter 聚合平台，支持多提供商模型',
  },
  {
    id: 'siliconcloud',
    name: 'SiliconCloud',
    baseUrl: 'https://api.siliconflow.cn/v1',
    apiKeyUrl: 'https://cloud.siliconflow.cn/account/ak',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'Qwen/Qwen2.5-72B-Instruct',
    description: '硅基流动 API，提供多种开源模型',
  },
  {
    id: 'together',
    name: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    apiKeyUrl: 'https://api.together.xyz/settings/api-keys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
    description: 'Together AI 云平台',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    baseUrl: 'http://localhost:11434',
    apiKeyUrl: 'https://ollama.com/download',
    sdkType: 'ollama',
    authType: 'none',
    openaiCompatible: true,
    checkModel: 'llama3.2',
    description: '本地运行的开源模型服务',
  },
  {
    id: 'azure',
    name: 'Azure OpenAI',
    apiKeyUrl: 'https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/OpenAI',
    sdkType: 'azure',
    authType: 'api-key',
    openaiCompatible: true,
    description: 'Azure OpenAI Service，需要配置 endpoint 和 apiVersion',
  },
  {
    id: 'xai',
    name: 'xAI',
    nameEn: 'Grok',
    baseUrl: 'https://api.x.ai/v1',
    apiKeyUrl: 'https://console.x.ai/',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'grok-2-latest',
    description: 'xAI（Grok）官方 API',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    baseUrl: 'https://api.cohere.ai',
    apiKeyUrl: 'https://dashboard.cohere.com/api-keys',
    sdkType: 'cohere',
    authType: 'bearer',
    openaiCompatible: false,
    checkModel: 'command-r-plus',
    description: 'Cohere 官方 API',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    apiKeyUrl: 'https://fireworks.ai/account/api-keys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    description: 'Fireworks AI 云平台',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    apiKeyUrl: 'https://www.perplexity.ai/settings/api',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'sonar',
    description: 'Perplexity AI 搜索增强 API',
  },
  {
    id: 'yi',
    name: '零一万物',
    nameEn: '01.AI',
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    apiKeyUrl: 'https://platform.lingyiwanwu.com/apikeys',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'yi-lightning',
    description: '零一万物官方 API，提供 Yi 系列模型',
  },
  {
    id: 'baichuan',
    name: '百川',
    nameEn: 'Baichuan',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    apiKeyUrl: 'https://platform.baichuan-ai.com/console/apikey',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'Baichuan4-Turbo',
    description: '百川智能官方 API',
  },
  {
    id: 'hunyuan',
    name: '腾讯混元',
    nameEn: 'Hunyuan',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    apiKeyUrl: 'https://console.cloud.tencent.com/hunyuan/api-key',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'hunyuan-standard',
    description: '腾讯混元官方 API',
  },
  {
    id: 'spark',
    name: '讯飞星火',
    nameEn: 'Spark',
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    apiKeyUrl: 'https://console.xfyun.cn/services/sparkai',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'generalv3.5',
    description: '科大讯飞星火官方 API',
  },
  {
    id: 'stepfun',
    name: '阶跃星辰',
    nameEn: 'Stepfun',
    baseUrl: 'https://api.stepfun.com/v1',
    apiKeyUrl: 'https://platform.stepfun.com/interface-key',
    sdkType: 'openai',
    authType: 'bearer',
    openaiCompatible: true,
    checkModel: 'step-1-8k',
    description: '阶跃星辰官方 API',
  },
];
